name: Setup Notes

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Recieve Notes
        shell: cmd
        run: |
          echo Hello CI. Remember to look at your repo.
