name: What time is It?

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Time
        shell: cmd
        run: |
          echo The current time is: %TIME%
          echo The current date is: %DATE%
